This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./index.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file index.acn....done (145 entries accepted, 0 rejected).
Sorting entries....done (1141 comparisons).
Generating output file index.acr....done (105 lines written, 0 warnings).
Output written in index.acr.
Transcript written in index.alg.
